name: "Semantic PR"

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize

jobs:
  main:
    name: Validate PR title
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          types: |
            fix
            feat
            chore
          # Discv5 repo uses https://github.blog/changelog/2022-05-11-default-to-pr-titles-for-squash-merge-commit-messages/
          validateSingleCommit: false
          validateSingleCommitMatchesPrTitle: false